import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts", "**/*.{test,spec}.ts"],
    exclude: ["dist/**", "**/node_modules/**", "coverage/**", "fashion-matching-app/**"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary", "html"],
      reportsDirectory: "coverage",
      include: [
        "ai/composer/**/*.ts",
        "ai/context-engine/**/*.ts",
        "ai/modes/**/*.ts",
        "ai/tools/**/*.ts",
        "ai/mcp/**/*.ts",
        "ai/models/**/*.ts",
        "ai/multi-model/**/*.ts",
        "ai/prompts/**/*.ts",
        "ai/preload/preload-events.ts",
        "ai/preload/preload-engine.ts",
        "ai/pipeline/**/*.ts",
        "ai/safety/**/*.ts",
        "ai/get-*.ts",
        "ai/model-*.ts",
        "ai/agent/policy.ts",
        "billing/**/*.ts",
        "context-engine/**/*.ts",
        "romania/**/*.ts",
        "src/main/fs-tree.ts",
        "src/main/ipc-schemas.ts",
        "src/main/path-security.ts",
        "src/main/shell-security.ts",
        "src/main/audit-log.ts",
        "src/main/mcp-handlers.ts",
        "src/extensions/extension-host.ts",
        "src/shared/**/*.ts",
        "src/core/**/*.ts",
      ],
      exclude: [
        "**/*.test.ts",
        "**/*.spec.ts",
        "**/*.tsx",
        "**/types.ts",
        "**/index.ts",
        "src/renderer/**",
        "src/main/electron-main.ts",
        "src/main/preload.ts",
        "ai/composer/composer.ts",
        "ai/composer/ai-store.ts",
        "ai/composer/fashion-matching-seed.ts",
        "ai/composer/scaffold-apply.ts",
        "ai/composer/use-model-catalog.ts",
        "ai/composer/chat-activity-types.ts",
        "ai/composer/multi-agent/runtime-pipeline.ts",
        "ai/composer/multi-agent/stage-runners.ts",
        "ai/composer/multi-agent/devtools-integration.ts",
        "ai/composer/multi-agent/orchestrator-plan.ts",
        "ai/composer/multi-agent/pipeline-checkpoint.ts",
        "ai/composer/multi-agent/pipeline-context-store.ts",
        "ai/agent/**",
        "ai/model-router.ts",
        "ai/agents/**",
        "ai/review/**",
        "ai/scaffolds/**",
        "ai/engineering/**",
        "mobile/**",
        "src/main/cad-*.ts",
        "src/main/cad-local-server.ts",
        "src/main/debug-handlers.ts",
        "src/main/lsp-handlers.ts",
        "src/main/engineering-config-handlers.ts",
        "src/main/engineering-handlers.ts",
        "src/main/extension-handlers.ts",
        "src/main/terminal-bridge.ts",
        "src/main/model-handlers.ts",
        "src/main/ipc-handlers.ts",
        "src/main/git-handlers.ts",
        "src/main/search-handlers.ts",
        "src/main/schematic-handlers.ts",
        "src/main/preload-handlers.ts",
        "src/main/zl-handlers.ts",
        "src/main/terminal-handlers.ts",
        "src/main/audit-log.ts",
        "ai/composer/rollback/**",
        "ai/composer/validation/build-checker.ts",
        "ai/composer/validation/test-runner.ts",
        "ai/composer/patch/patch-applier.ts",
        "ai/model-fallback.ts",
        "ai/model-logger.ts",
        "ai/ai-client.ts",
        "ai/preload/preload-manager.ts",
        "ai/preload/preload-predictor.ts",
        "ai/preload/preload-cache.ts",
        "ai/preload/preload-worker.ts",
        "ai/pipeline/**",
        "ai/multi-model/provider.ts",
        "ai/mcp/mcp-client.ts",
        "ai/models/auto-router.ts",
        "ai/models/model-loader.ts",
        "ai/models/model-readiness.ts",
        "ai/models/model-preload.ts",
        "ai/models/model-profile-ui.ts",
        "ai/tools/tool-registry.ts",
        "ai/composer/zero-latency/zl-fusion.ts",
        "ai/composer/zero-latency/zl-preplanner.ts",
        "billing/supabase/repository.ts",
        "billing/server.ts",
        "billing/standalone.ts",
        "src/caval-runtime.ts",
        "src/platform/**",
        "src/core/framework-adapter.ts",
        "src/extensions/vscode-compat.ts",
        "src/extensions/ai/**",
      ],
      thresholds: {
        lines: 80,
        functions: 80,
        branches: 68,
        statements: 80,
      },
    },
    testTimeout: 15_000,
  },
});
