/** All menu command IDs emitted from electron-main.ts via caval:menu-command */
export const MENU_COMMAND_IDS = [
  'new-file',
  'save',
  'save-as',
  'open-settings',
  'find',
  'replace',
  'find-in-files',
  'replace-in-files',
  'toggle-line-comment',
  'toggle-block-comment',
  'emmet-expand',
  'selection-expand',
  'selection-shrink',
  'copy-line-up',
  'copy-line-down',
  'move-line-up',
  'move-line-down',
  'cursor-above',
  'cursor-below',
  'palette',
  'open-view',
  'split-editor',
  'single-editor',
  'toggle-sidebar',
  'view-explorer',
  'view-search',
  'view-source-control',
  'view-run',
  'view-extensions',
  'view-problems',
  'view-output',
  'view-debug-console',
  'word-wrap',
  'go-back',
  'go-forward',
  'last-edit-location',
  'switch-editor',
  'switch-group',
  'go-to-file',
  'go-to-symbol-workspace',
  'go-to-symbol-editor',
  'go-to-definition',
  'go-to-declaration',
  'go-to-type-definition',
  'go-to-implementations',
  'add-symbol-current-chat',
  'go-to-references',
  'add-symbol-new-chat',
  'go-to-line',
  'go-to-bracket',
  'next-problem',
  'previous-problem',
  'next-change',
  'previous-change',
  'run-debug',
  'run-without-debug',
  'stop-debug',
  'restart-debug',
  'run-active-file',
  'run-selected-text',
  'add-run-config',
  'terminal-new',
  'terminal-split',
  'task-run',
  'task-build',
  'tasks-configure',
  'tasks-default-build',
  'editor-playground',
  'accessibility',
  'feedback',
  'license',
  'process-explorer',
  'check-updates',
  'about',
] as const;

export type MenuCommandId = (typeof MENU_COMMAND_IDS)[number];

export function isMenuCommandId(command: string): command is MenuCommandId {
  return (MENU_COMMAND_IDS as readonly string[]).includes(command);
}
